### PR TITLE
Add "use webcam" support 

### PR DESCRIPTION
**Pull request by xdumaine**
This 
- creates a webcam view that 
- gets rendered as a button (with invisible video element) inside the editor view and is
- hidden in browsers unsupported
- renders the video stream to the canvas periodically

I've never worked in backbone before, so all feedback is welcome!

### CODE REVIEW

**Comment by alishalisha** [comment]
@xdumaine this is amazing!!! :+1: is it possible to add a "take photo" button? currently the only way to save the photo is to go ahead and download it... which could be fine! the other things that i can do myself after merging is:
1. UX thing: move "or take photo with webcam" to be below "drop image here" 
2. place the "what is this?" and "how to contribute" paragraphs back on the right side

lmk if you have any thoughts. this is great :clap:

**Comment by xdumaine** [comment]
@alishalisha I'm a little confused - where is the "what is this" and "how to contribute" information? It's not in the source anywhere.

**Comment by alishalisha** [comment]
@xdumaine whoa, that is my bad - I never merged the `gh-pages` branch into `master`. I just did — should see it now.

**Comment by xdumaine** [comment]
Ok, all up to date: 
ilooklikeanengineer

**Comment by alishalisha** [comment]
@xdumaine awesome! thank you!

**Pull request merged**
